//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmazonInvoiceGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmazonInvoiceGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap amazon_logo_tiny {
            get {
                object obj = ResourceManager.GetObject("amazon_logo_tiny", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;html&gt;&lt;head&gt;
        ///&lt;meta http-equiv=&quot;content-type&quot; content=&quot;text/html; charset=windows-1252&quot;&gt;&lt;script src=&quot;AmazonOrderTemplate_files/csm-base-v2-min-858824421.js&quot; async=&quot;&quot;&gt;&lt;/script&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;var ue_t0=ue_t0||+new Date();&lt;/script&gt;
        ///&lt;script type=&quot;text/javascript&quot;&gt;
        ///var ue_id=&apos;0MY4A8R9BX5KTGFXJPD7&apos;,
        ///ue_csm = window,
        ///ue_err_chan = &apos;jserr-rw&apos;,
        ///ue = {};
        ///ue_csm.ue_hob=ue_csm.ue_hob||+new Date();(function(c){var a=c.ue,b=(Date.now||function(){return +new Date()});a.lr=[];a.log=function(f,e,d){i [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AmazonOrderTemplate {
            get {
                return ResourceManager.GetString("AmazonOrderTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* begin popover/amzPopoverCss.css */
        ///.ap_popover{position:absolute;outline:0}
        ///.ap_body{height:100%;min-height:36px;position:relative;background-color:#fff;margin:0 17px}
        ///.ap_popover_sprited .ap_body .ap_left-arrow,.ap_body .ap_left{width:17px;height:100%;position:absolute;top:0;left:-17px;background-attachment:scroll;background-repeat:repeat-y}
        ///.ap_popover_sprited .ap_body .ap_left{background-position:0 top}
        ///.ap_popover_sprited .ap_body .ap_right-arrow,.ap_body .ap_right{width:17px;height:100%;position:abs [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string site_wide_6800426958 {
            get {
                return ResourceManager.GetString("site_wide_6800426958", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///body { 
        ///  background-color: #FFFFFF; 
        ///}
        ///* html body { 
        ///  margin-top: 0px; 
        ///}
        ///h2.small, h2.h1, h2.h3color { 
        ///  margin-bottom: 0em; 
        ///}
        ///.serif { 
        ///  font-family: times, serif;
        ///}
        ///.h1, .h3color {
        ///  color: #E47911;
        ///}
        ///
        ///a:active {
        ///  color: #FF9933;
        ///}
        ///a:visited {
        ///  color: #996633;
        ///}
        ///a:link {
        ///  color: #004B91;
        ///}
        ///a.noclick, a.noclick:visited {
        ///  color: #000000;
        ///}
        ///
        ///.noLinkDecoration a {
        ///  text-decoration: none;
        ///  border-bottom: none;
        ///}
        ///.noLinkDecoration a:hover {
        ///  text-decoration: underline;
        ///}
        ///.noLinkDecoration a.dyna [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string websiteGlobalCSS_websiteGlobal_10346 {
            get {
                return ResourceManager.GetString("websiteGlobalCSS_websiteGlobal_10346", resourceCulture);
            }
        }
    }
}
